module.exports = {
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  UPDATE_ACCOUNT: "UPDATE_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  CREATE_STUDY: "CREATE_STUDY",
  UPDATE_STUDY: "UPDATE_STUDY",
  DELETE_STUDY: "DELETE_STUDY",
  NEW_PARTICIPANT: "NEW_PARTICIPANT",
  CHANGE_PARTICIPANT_STATUS: "NEW_PARTICIPANT",
  CREATE_MEETING: "CREATE_MEETING",
  UPDATE_MEETING: "UPDATE_MEETING",
  DELETE_MEETING: "DELETE_MEETING",
  NEW_MESSAGE: "NEW_MESSAGE",
};
