module.exports = {
  //SHARED
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  MEETING_NOW: "MEETING_NOW",

  //RESEARCHER
  CREATE_STUDY: "CREATE_STUDY",
  DELETE_STUDY: "DELETE_STUDY",
  PARTICIPANT_ENROLLED: "PARTICIPANT_ENROLLED",
  PARTICIPANT_CONFIRMED_MEETING: "PARTICIPANT_CONFIRMED_MEETING",
  PARTICIPANT_CONFIRMED_REMINDER: "PARTICIPANT_CONFIRMED_REMINDER",

  //PARTICIPANT
  RESEARCHER_SENT_MESSAGE: "RESEARCHER_SENT_MESSAGE",
  RESEARCHER_CREATED_MEETING: "RESEARCHER_CREATED_MEETING",
  RESEARCHER_UPDATED_MEETING: "RESEARCHER_UPDATED_MEETING",
  RESEARCHER_DELETED_MEETING: "RESEARCHER_DELETED_MEETING",
  RESEARCHER_CREATED_REMINDER: "RESEARCHER_CREATED_REMINDER",
  RESEARCHER_UPDATED_REMINDER: "RESEARCHER_UPDATED_REMINDER",
  RESEARCHER_DELETED_REMINDER: "RESEARCHER_DELETED_REMINDER",
  RESEARCHER_CHANGED_PARTICIPANT_STATUS: "RESEARCHER_CHANGED_PARTICIPANT_STATUS",
  REMINDER_NOW: "REMINDER_NOW",
};
